{
 "title": "YouTube Scraping Project 2025 AS3",
 "description": "DashBoard Grafana du projet de WebScraping qui est une solution complète pour le webscraping Youtube, avec une infrastructure conteneurisée et des outils de monitoring.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Indicateurs pour Flask", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% de la mémoire virtuelle utilisée au processus",
   "type": "gauge",
   "description": "Surveille la consommation de mémoire physique par Celery, permettant de détecter des fuites mémoire ou une utilisation excessive.",
   "gridPos": { "h": 5, "w": 11, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"flask\"} / 3949384320 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation de la mémoire",
   "type": "timeseries",
   "description": "Montre la mémoire consommée par le processus Flask.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"flask\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps écoulé depuis le démarrage du processus (en secondes)",
   "type": "gauge",
   "description": "Calcule le temps écoulé depuis le démarrage du processus (en secondes), offrant une indication sur sa continuité opérationnelle.",
   "gridPos": { "h": 5, "w": 11, "x": 1, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"flask\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Indicateurs pour Celery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Nombre de workers actifs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "celery_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pourcentage de succès des tâches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(celery_tasks{state=\"SUCCESS\"} / celery_tasks) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence moyenne des tâches (5 min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(celery_task_latency_sum[5m])) / sum(rate(celery_task_latency_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}